[[env_vars]]
key = "BUCKET_AND_PREFIX"
value = "backups"

[commands]
create_backup = 'echo "$BACKUP_NAME"'
create_for_write = 'echo "s3://$BUCKET_AND_PREFIX/$BACKUP_HANDLE/$FILE_NAME" && exec >&- && aws --endpoint-url $AWS_S3_ENDPOINT_URL s3 cp - "s3://$BUCKET/$BACKUP_HANDLE/$FILE_NAME"'
open_for_read = 'aws --endpoint-url $AWS_S3_ENDPOINT_URL s3 cp "$FILE_HANDLE" -'
save_metadata_line= 'aws --endpoint-url $AWS_S3_ENDPOINT_URL s3 cp - "s3://$BUCKET_AND_PREFIX/metadata/$FILE_NAME"'
list_metadata_files = 'aws --endpoint-url $AWS_S3_ENDPOINT_URL s3 ls s3://$BUCKET_AND_PREFIX/metadata/ | sed -ne "s/.* //p" | xargs -I{} echo s3://$BUCKET/metadata/{}'